'use client';
import { ReactNode } from 'react';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell,TableFooter } from '@/components/ui/table';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { money,number } from '@/lib/finance';
export function Choice({value,onChange,options,label,id,disabled=false}:{value:string;onChange:(value:string)=>void;options:{value:string;label:string}[];label:string;id?:string;disabled?:boolean}){return <Select dir="rtl" value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger id={id} className="finance-select" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent position="popper">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export function Metric({label,value,unit='ريال',note,icon,color=''}:{label:string;value:string;unit?:string;note:string;icon:ReactNode;color?:string}){return <article className={`kpi ${color}`}><div className="kpi-label"><span>{label}</span>{icon}</div><div className="kpi-number"><strong>{value}</strong>{unit&&<span>{unit}</span>}</div><small>{note}</small></article>}
export function Amount({value}:{value:number}){return <span className="money" dir="ltr">{money(value)}</span>}
export function Margin({profit,revenue}:{profit:number;revenue:number}){return <span className={profit<0?'negative':'positive'} dir="ltr">{revenue>0?`${number(profit/revenue*100,1)}%`:'—'}</span>}
export function DataTable({headers,children,footer,caption}:{headers:string[];children:ReactNode;footer?:ReactNode;caption?:string}){return <Table className="finance-table" aria-label={caption}><TableHeader><TableRow>{headers.map((h,i)=><TableHead key={`${h}-${i}`}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody>{footer&&<TableFooter>{footer}</TableFooter>}</Table>}
export { TableRow as Row,TableCell as Cell };
export function EmptyState({title='لا توجد سجلات',description,children}:{title?:string;description:string;children?:ReactNode}){return <Empty className="empty-panel"><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{children}</Empty>}
export function Distribution({items,colors=['#deb65f','#60ccb2','#839ce1','#b499d8','#e78d83','#6c9ec3']}:{items:{name:string;value:number}[];colors?:string[]}){const total=items.reduce((s,r)=>s+r.value,0);return total===0?<div className="blank-chart">لا توجد قيم مسجلة لهذه المقارنة.</div>:<div className="distribution">{items.map((item,i)=><div key={item.name}><div className="distribution-label"><span>{item.name}</span><b dir="ltr">{money(item.value)} <small style={{display:'inline',fontFamily:'Plex'}}>ريال</small></b></div><div className="distribution-track" aria-hidden="true"><div style={{width:`${item.value/total*100}%`,background:colors[i%colors.length]}}/></div><small>{number(item.value/total*100,1)}% من الإجمالي</small></div>)}</div>}
