'use client';
import { ArrowUpRight,Wallet,ReceiptText,ChartNoAxesCombined,TrendingUp,Package,Percent,Pencil,Trash2,Flame } from 'lucide-react';
import { MONTHS,FinanceData,Sale,Expense,money,number,summarize,monthly,filterMonth,groupProducts,groupAmounts } from '@/lib/finance';
import { Metric,DataTable,Row,Cell,Amount,Margin,Distribution,EmptyState } from './finance-ui';
import { FinanceChart } from './finance-chart';
export type RecordSelection={kind:'sale';row:Sale}|{kind:'expense';row:Expense};
type Actions={actual:boolean;onEdit:(record:RecordSelection)=>void;onDelete:(record:RecordSelection)=>void};
const period=(month:string)=>month==='all'?'يناير — ديسمبر 2026':`${MONTHS[Number(month)]} 2026`;
function MonthTable({data}:{data:FinanceData}){const rows=monthly(data),total=summarize(data),peak=Math.max(...rows.map(r=>r.revenue));return <div className="card table-card"><div className="table-title"><h2>التفاصيل المالية لجميع الأشهر</h2><small>12 شهرًا · سنة 2026</small></div><DataTable caption="الإيرادات والتكاليف والأرباح شهريًا لسنة 2026" headers={['الشهر','الإيرادات','تكلفة المنتجات','تشغيل ثابت','تشغيل متغير','إجمالي المصروفات','صافي الربح','هامش الربح']} footer={<Row><Cell>إجمالي السنة</Cell><Cell><Amount value={total.revenue}/></Cell><Cell><Amount value={total.direct}/></Cell><Cell><Amount value={total.fixed}/></Cell><Cell><Amount value={total.variable}/></Cell><Cell><Amount value={total.totalCost}/></Cell><Cell><Amount value={total.profit}/></Cell><Cell><Margin profit={total.profit} revenue={total.revenue}/></Cell></Row>}>{rows.map(r=><Row key={r.index}><Cell><div className="row-name">{r.name}{peak>0&&r.revenue===peak&&<small>ذروة الإيراد</small>}</div></Cell>{[r.revenue,r.direct,r.fixed,r.variable,r.totalCost].map((v,i)=><Cell key={i}>{r.records?<Amount value={v}/>:<span className="muted-text">—</span>}</Cell>)}<Cell className={r.profit<0?'negative':'positive'}>{r.records?<Amount value={r.profit}/>:'—'}</Cell><Cell>{r.records?<Margin profit={r.profit} revenue={r.revenue}/>:'—'}</Cell></Row>)}</DataTable><p className="table-note">المبالغ بالريال وغير شاملة الضريبة. صافي الربح = الإيرادات − تكلفة المنتجات − المصروفات الثابتة − المصروفات المتغيرة. «—» تعني عدم وجود سجلات للشهر.</p></div>}
export function Overview({data,month,onMonth}:{data:FinanceData;month:string;onMonth:(m:string)=>void}){
 const filtered={sales:filterMonth(data.sales,month),expenses:filterMonth(data.expenses,month)},s=summarize(filtered),year=summarize(data),months=monthly(data),recorded=months.filter(m=>m.records);
 const peak=months.filter(m=>m.revenue>0).sort((a,b)=>b.revenue-a.revenue)[0],qtyPeak=months.filter(m=>m.qty>0).sort((a,b)=>b.qty-a.qty)[0],profitPeak=recorded.slice().sort((a,b)=>b.profit-a.profit)[0];
 const allProducts=groupProducts(filtered.sales),bestSelling=allProducts.slice().sort((a,b)=>b.qty-a.qty).slice(0,5),mostProfitable=allProducts.slice().sort((a,b)=>b.profit-a.profit).slice(0,5),product=mostProfitable[0],max=Math.max(1,...months.map(m=>m.revenue));
 return <><div className="kpi-row"><Metric label="إجمالي الإيرادات" value={money(s.revenue)} note={period(month)} icon={<ArrowUpRight/>} color="gold"/><Metric label="إجمالي المصروفات" value={money(s.totalCost)} note="تكلفة المنتجات + الثابتة + المتغيرة" icon={<ReceiptText/>}/><Metric label={s.profit<0?'صافي الخسارة':'صافي الربح'} value={money(s.profit)} note="بعد احتساب جميع المصروفات المسجلة" icon={<Wallet/>} color={s.profit<0?'red':'green'}/><Metric label="هامش صافي الربح" value={s.margin===null?'—':number(s.margin,1)} unit={s.margin===null?'':'%'} note={`${number(s.qty)} وحدة مباعة في الفترة`} icon={<Percent/>}/></div>
 <div className="grid-main"><section className="card"><div className="card-head"><div><h2>الإيرادات والمصروفات وصافي الربح</h2><p>المقارنة السنوية كاملة · الأشهر من 01 إلى 12</p></div><span>2026</span></div><FinanceChart rows={months}/><p className="chart-caption">المحور الأفقي يمثل أشهر السنة، والقيم بالريال. مرّر على الشهر لعرض تفاصيله.</p></section><aside className="card peak-panel"><div className="peak-label"><Flame/>ذروة الإيرادات خلال السنة</div><div className="peak-name">{peak?.name||'—'}</div><div className="peak-value">{peak?<><b dir="ltr">{money(peak.revenue)}</b> ريال إيرادات</>:'بانتظار بيانات المبيعات'}</div><p>{peak&&year.revenue?`يمثل ${number(peak.revenue/year.revenue*100,1)}% من إيرادات السنة المسجلة. حضّر المخزون والموظفين وفق الطلب الفعلي، وراجع هذا المؤشر شهريًا.`:'تظهر أشهر الذروة عند إضافة إيرادات المنتجات. تعتمد المقارنة على السجلات الموجودة فقط.'}</p><div className="peak-details"><div><span>أعلى كمية مباعة</span><b>{qtyPeak?`${qtyPeak.name} · ${number(qtyPeak.qty)}`:'—'}</b></div><div><span>أفضل نتيجة مالية</span><b>{profitPeak?.name||'—'}</b></div><div><span>أشهر بها سجلات</span><b>{recorded.length} / 12</b></div></div></aside></div>
 <section className="card full"><div className="card-head"><div><h2>خريطة النشاط الشهري</h2><p>اختر شهرًا لعرض مؤشرات الفترة. مقارنة السنة تظل ظاهرة أعلاه.</p></div><span>الإيرادات · ريال</span></div><div className="month-strip">{months.map(r=><button key={r.index} className={`month-tile${month===String(r.index)?' active':''}${peak?.index===r.index?' peak':''}`} onClick={()=>onMonth(month===String(r.index)?'all':String(r.index))} aria-pressed={month===String(r.index)} style={{background:r.records?`rgba(222,182,95,${.025+r.revenue/max*.14})`:undefined}}><span>{r.name}</span><b dir="ltr">{r.records?money(r.revenue):'—'}</b><small>{r.records?`${number(r.qty)} وحدة`:'لا سجلات'}</small></button>)}</div></section>
 <div className="grid-two"><section className="card"><div className="card-head"><div><h2>مصادر الإيراد حسب التصنيف</h2><p>{period(month)}</p></div><Package size={19} color="#deb65f"/></div><Distribution items={groupAmounts(filtered.sales.map(r=>({category:r.category,amount:r.revenue})))}/></section><section className="card"><div className="card-head"><div><h2>أين تذهب المصروفات؟</h2><p>تفاصيل التكلفة والتشغيل للفترة المختارة</p></div><ReceiptText size={19} color="#e78d83"/></div><Distribution items={[{name:'تكلفة المنتجات المباعة',value:s.direct},...groupAmounts(filtered.expenses.map(e=>({category:e.category,amount:e.amount})))].filter(r=>r.value>0)}/></section></div>
 <div className="grid-two"><section className="card table-card"><div className="card-head"><div><h2>العصائر الأكثر مبيعًا</h2><p>مرتبة حسب عدد الوحدات المباعة · {period(month)}</p></div><TrendingUp size={19} color="#60ccb2"/></div>{bestSelling.length?<DataTable caption="العصائر الأكثر مبيعًا" headers={['العصير','الكمية المباعة','الإيرادات','الهامش']}>{bestSelling.map(r=><Row key={`sold-${r.product}-${r.category}`}><Cell><div className="row-name">{r.product}<small>{r.category}</small></div></Cell><Cell>{number(r.qty)} وحدة</Cell><Cell><Amount value={r.revenue}/></Cell><Cell><Margin profit={r.profit} revenue={r.revenue}/></Cell></Row>)}</DataTable>:<EmptyState description="أضف سجلات المنتجات لتظهر العصائر الأكثر مبيعًا."/>}</section><section className="card table-card"><div className="card-head"><div><h2>العصائر الأكثر ربحًا</h2><p>مرتبة حسب ربح المنتج قبل مصاريف التشغيل · {period(month)}</p></div><Wallet size={19} color="#deb65f"/></div>{mostProfitable.length?<DataTable caption="العصائر الأكثر ربحًا" headers={['العصير','ربح المنتج','الإيرادات','الهامش']}>{mostProfitable.map(r=><Row key={`profit-${r.product}-${r.category}`}><Cell><div className="row-name">{r.product}<small>{r.category}</small></div></Cell><Cell className={r.profit<0?'negative':'positive'}><Amount value={r.profit}/></Cell><Cell><Amount value={r.revenue}/></Cell><Cell><Margin profit={r.profit} revenue={r.revenue}/></Cell></Row>)}</DataTable>:<EmptyState description="أضف تكاليف المنتجات لتظهر العصائر الأكثر ربحًا."/>}</section></div>
 <div className="insight-grid"><article className="insight"><h3>المنتج الأعلى ربحًا في الفترة</h3><p>{product?`${product.product} يحقق ربحًا قبل التشغيل قدره ${money(product.profit)} ريال، من إيرادات ${money(product.revenue)} ريال.`:'أضف سجلات المنتجات لتظهر مقارنة ربحيتها.'}</p></article><article className="insight"><h3>تكلفة تشغيل المحل</h3><p>الثابتة والمتغيرة معًا: {money(s.fixed+s.variable)} ريال. {s.revenue>0?`تمثل ${number((s.fixed+s.variable)/s.revenue*100,1)}% من إيرادات الفترة.`:'تظهر نسبتها بعد تسجيل الإيرادات.'}</p></article><article className="insight"><h3>ربح المنتج وصافي ربح المحل</h3><p>ربح المنتجات قبل التشغيل {money(s.gross)} ريال. بعد خصم مصروفات التشغيل يصبح صافي النتيجة {money(s.profit)} ريال.</p></article></div>
 <div className="section-heading"><div><h2>كشف السنة بالكامل</h2><p>مرجع واحد لمراجعة أرقام كل شهر.</p></div></div><MonthTable data={data}/></>;
}
function RecordActions({selection,actual,onEdit,onDelete}:Actions&{selection:RecordSelection}){return actual?<div className="table-actions"><button className="icon-button" title="تعديل السجل" aria-label={`تعديل ${selection.kind==='sale'?selection.row.product:selection.row.title}`} onClick={()=>onEdit(selection)}><Pencil/></button><button className="icon-button danger" title="حذف السجل" aria-label={`حذف ${selection.kind==='sale'?selection.row.product:selection.row.title}`} onClick={()=>onDelete(selection)}><Trash2/></button></div>:<span className="muted-text">افتراضي</span>}
export function SalesLedger({sales,...actions}:Actions&{sales:Sale[]}){const s=summarize({sales,expenses:[]});return <div className="card table-card"><div className="table-title"><h2>سجل الإيرادات وتكاليف المنتجات</h2><small>{number(sales.length)} سجل</small></div>{!sales.length?<EmptyState description="أضف إيراد منتج من صفحة إدخال البيانات، أو غيّر الفترة المختارة."/>:<DataTable caption="سجل إيرادات المنتجات" headers={['التاريخ','اسم المنتج','التصنيف','الكمية','الإيراد','تكلفة المنتج','ربح المنتج','الهامش','الإجراءات']} footer={<Row><Cell colSpan={3}>الإجمالي</Cell><Cell>{number(s.qty)}</Cell><Cell><Amount value={s.revenue}/></Cell><Cell><Amount value={s.direct}/></Cell><Cell><Amount value={s.gross}/></Cell><Cell><Margin profit={s.gross} revenue={s.revenue}/></Cell><Cell/></Row>}>{sales.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(r=><Row key={r.id}><Cell><span dir="ltr">{r.date}</span></Cell><Cell title={r.notes}>{r.product}</Cell><Cell>{r.category}</Cell><Cell>{number(r.qty)}</Cell><Cell className="gold-text"><Amount value={r.revenue}/></Cell><Cell><Amount value={r.cost}/></Cell><Cell className={r.revenue-r.cost<0?'negative':'positive'}><Amount value={r.revenue-r.cost}/></Cell><Cell><Margin profit={r.revenue-r.cost} revenue={r.revenue}/></Cell><Cell><RecordActions selection={{kind:'sale',row:r}} {...actions}/></Cell></Row>)}</DataTable>}<p className="table-note">ربح المنتج هنا قبل مصروفات التشغيل. تكلفة كل سجل تدخل المصروفات مرة واحدة تلقائيًا. تاريخ الملخص الشهري يحدد الشهر الذي يُنسب إليه.</p></div>}
export function Revenue({data,month,category,...actions}:Actions&{data:FinanceData;month:string;category:string}){
 const yearSales=category==='all'?data.sales:data.sales.filter(s=>s.category===category),sales=filterMonth(yearSales,month),s=summarize({sales,expenses:[]}),groups=groupProducts(sales),months=monthly({sales:yearSales,expenses:[]});
 return <><div className="kpi-row"><Metric label="إجمالي الإيرادات" value={money(s.revenue)} note={period(month)} icon={<ArrowUpRight/>} color="gold"/><Metric label="ربح المنتجات قبل التشغيل" value={money(s.gross)} note="الإيرادات ناقص تكلفة المنتجات" icon={<Wallet/>} color={s.gross<0?'red':'green'}/><Metric label="الكمية المباعة" value={number(s.qty)} unit="وحدة" note={`${groups.length} منتجات في الفترة`} icon={<Package/>}/><Metric label="هامش المنتجات" value={s.revenue?number(s.gross/s.revenue*100,1):'—'} unit={s.revenue?'%':''} note="قبل الإيجار وبقية مصروفات التشغيل" icon={<Percent/>}/></div><div className="card full"><div className="card-head"><div><h2>تطور الإيرادات وتكلفة المنتجات شهريًا</h2><p>السنة كاملة · {category==='all'?'جميع التصنيفات':category}</p></div><span>2026</span></div><FinanceChart rows={months} kind="revenue"/><p className="chart-caption">المقارنة تعرض الشهور الاثني عشر دائمًا، بينما المؤشرات والسجلات تتبع الشهر المختار.</p></div><div className="grid-two"><section className="card"><div className="card-head"><div><h2>الإيرادات حسب التصنيف</h2><p>{period(month)}</p></div></div><Distribution items={groupAmounts(sales.map(r=>({category:r.category,amount:r.revenue})))}/></section><section className="card"><div className="card-head"><div><h2>أعلى المنتجات في الإيرادات</h2><p>أفضل خمسة منتجات في الفترة</p></div></div><Distribution items={groups.slice(0,5).map(r=>({name:r.product,value:r.revenue}))}/></section></div><div className="section-heading"><div><h2>مقارنة ربحية المنتجات</h2><p>الإيراد والتكلفة والهامش لكل منتج وتصنيف.</p></div></div><div className="card table-card">{!groups.length?<EmptyState description="لا توجد منتجات ضمن الفترة والتصنيف المختارين."/>:<DataTable caption="مقارنة ربحية المنتجات" headers={['المنتج','التصنيف','الكمية','الإيرادات','تكلفة المنتجات','الربح قبل التشغيل','هامش المنتج']}>{groups.map(r=><Row key={`${r.product}-${r.category}`}><Cell>{r.product}</Cell><Cell>{r.category}</Cell><Cell>{number(r.qty)}</Cell><Cell><Amount value={r.revenue}/></Cell><Cell><Amount value={r.cost}/></Cell><Cell className={r.profit<0?'negative':'positive'}><Amount value={r.profit}/></Cell><Cell><Margin profit={r.profit} revenue={r.revenue}/></Cell></Row>)}</DataTable>}</div><div className="section-heading"><div><h2>الإيرادات كاملة</h2><p>جميع السجلات المطابقة للفترة والتصنيف، مع إمكانية تعديل بيانات المحل.</p></div></div><SalesLedger sales={sales} {...actions}/></>;
}
export function Expenses({data,month,expenseType,...actions}:Actions&{data:FinanceData;month:string;expenseType:string}){
 const selected:FinanceData={sales:['all','product'].includes(expenseType)?data.sales:[],expenses:expenseType==='all'?data.expenses:expenseType==='product'?[]:data.expenses.filter(e=>e.type===expenseType)};
 const filtered={sales:filterMonth(selected.sales,month),expenses:filterMonth(selected.expenses,month)},s=summarize(filtered),months=monthly(selected);
 const ledger=[...filtered.sales.map(r=>({id:r.id,date:r.date,title:`تكلفة ${r.product}`,category:r.category,type:'product',amount:r.cost,selection:{kind:'sale',row:r} as RecordSelection})),...filtered.expenses.map(r=>({...r,selection:{kind:'expense',row:r} as RecordSelection}))].sort((a,b)=>b.date.localeCompare(a.date));
 return <><div className="kpi-row"><Metric label="إجمالي المصروفات" value={money(s.totalCost)} note={period(month)} icon={<ReceiptText/>} color="gold"/><Metric label="تكلفة المنتجات" value={money(s.direct)} note="تلقائيًا من سجلات إيرادات المنتجات" icon={<Package/>}/><Metric label="مصروفات ثابتة" value={money(s.fixed)} note="مثل الإيجار والرواتب والاشتراكات" icon={<Wallet/>}/><Metric label="مصروفات متغيرة" value={money(s.variable)} note="مثل الكهرباء والصيانة والتسويق" icon={<ChartNoAxesCombined/>}/></div><div className="card full"><div className="card-head"><div><h2>المصروفات على مدار السنة</h2><p>الشهور من 01 إلى 12 · حسب نوع المصروف المختار</p></div><span>2026</span></div><FinanceChart rows={months} kind="expenses"/><p className="chart-caption">ارتفاع المصروفات يظهر مع تفصيل مصدر الزيادة بين المنتجات والتشغيل الثابت والمتغير.</p></div><div className="grid-two"><section className="card"><div className="card-head"><div><h2>توزيع إجمالي المصروفات</h2><p>{period(month)}</p></div></div><Distribution items={[{name:'تكلفة المنتجات',value:s.direct},{name:'مصروفات ثابتة',value:s.fixed},{name:'مصروفات متغيرة',value:s.variable}].filter(r=>r.value>0)}/></section><section className="card"><div className="card-head"><div><h2>مصروفات التشغيل حسب البند</h2><p>جميع البنود الثابتة والمتغيرة المسجلة للفترة</p></div></div><Distribution items={groupAmounts(filtered.expenses.map(r=>({category:r.category,amount:r.amount})))}/></section></div><div className="section-heading"><div><h2>المصروفات كاملة</h2><p>تشمل تكلفة المنتجات ومصاريف المحل دون تكرار التكلفة.</p></div><span>{ledger.length} سجل</span></div><div className="card table-card">{!ledger.length?<EmptyState description="لا توجد مصروفات ضمن هذه الفترة. أضف مصروف تشغيل أو سجل تكلفة منتج."/>:<DataTable caption="سجل جميع المصروفات" headers={['التاريخ','المصروف','البند / التصنيف','نوع المصروف','القيمة (ريال)','المصدر','الإجراءات']} footer={<Row><Cell colSpan={4}>إجمالي المصروفات للفترة</Cell><Cell><Amount value={s.totalCost}/></Cell><Cell colSpan={2}/></Row>}>{ledger.map(r=><Row key={`${r.type}-${r.id}`}><Cell><span dir="ltr">{r.date}</span></Cell><Cell>{r.title}</Cell><Cell>{r.category}</Cell><Cell><span className={`badge ${r.type}`}>{r.type==='product'?'تكلفة منتج':r.type==='fixed'?'ثابت':'متغير'}</span></Cell><Cell><Amount value={r.amount}/></Cell><Cell>{r.type==='product'?'من سجل الإيراد':'مصروف تشغيل'}</Cell><Cell><RecordActions selection={r.selection} {...actions}/></Cell></Row>)}</DataTable>}<p className="table-note">تعديل تكلفة منتج يحدّث سجل الإيراد الأصلي. حذف سجل منتج يحذف إيراده وتكلفته معًا. حذف مصروف شهري متكرر يخص الشهر المحدد فقط.</p></div></>;
}
