'use client';
import { ResponsiveContainer,ComposedChart,Bar,Line,XAxis,YAxis,CartesianGrid,Tooltip } from 'recharts';
import { money,number,monthly } from '@/lib/finance';
type MonthRow=ReturnType<typeof monthly>[number];
export function FinanceChart({rows,kind='overview'}:{rows:MonthRow[];kind?:'overview'|'revenue'|'expenses'}){
 const hasRecords=rows.some(r=>r.records>0);
 const data=rows.map(r=>({...r,revenue:r.records?r.revenue:null,totalCost:r.records?r.totalCost:null,profit:r.records?r.profit:null,direct:r.records?r.direct:null,fixed:r.records?r.fixed:null,variable:r.records?r.variable:null}));
 const colors=kind==='overview'?[['الإيرادات','#deb65f'],['المصروفات','#e78d83'],['صافي الربح','#60ccb2']]:kind==='revenue'?[['الإيرادات','#deb65f'],['تكلفة المنتجات','#e78d83']]:[['تكلفة المنتجات','#60ccb2'],['مصروفات ثابتة','#ad95dc'],['مصروفات متغيرة','#e78d83']];
 return <><div className="chart-legend">{colors.map(([name,color])=><span key={name}><i style={{background:color}}/>{name}</span>)}</div><div className="chart-frame">{hasRecords?<ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:20,right:14,left:0,bottom:5}} accessibilityLayer><CartesianGrid stroke="#2a3d54" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false} interval={0} tick={{fill:'#a5b5ca',fontSize:12,fontFamily:'Plex'}} tickFormatter={(_,i)=>String(i+1).padStart(2,'0')} height={28}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#8fa5bf',fontSize:12}} tickFormatter={v=>Math.abs(v)>=100000?`${number(v/100000,0)}k`:number(v/100)} width={52}/><Tooltip content={({active,payload,label})=>active&&payload?.length?<div className="chart-tooltip"><strong>{String(label)} 2026</strong>{payload.map((p,i)=><div key={`${p.dataKey}-${i}`}><span style={{color:p.color}}>{p.name}</span><b dir="ltr">{money(Number(p.value))} <span style={{fontFamily:'Plex'}}>ريال</span></b></div>)}</div>:null}/>{kind==='expenses'?<><Bar dataKey="direct" name="تكلفة المنتجات" stackId="cost" fill="#60ccb2" maxBarSize={35}/><Bar dataKey="fixed" name="مصروفات ثابتة" stackId="cost" fill="#ad95dc" maxBarSize={35}/><Bar dataKey="variable" name="مصروفات متغيرة" stackId="cost" fill="#e78d83" radius={[4,4,0,0]} maxBarSize={35}/></>:<><Bar dataKey="revenue" name="الإيرادات" fill="#deb65f" radius={[4,4,0,0]} maxBarSize={23}/><Bar dataKey={kind==='revenue'?'direct':'totalCost'} name={kind==='revenue'?'تكلفة المنتجات':'المصروفات'} fill="#cf827e" radius={[4,4,0,0]} maxBarSize={23}/>{kind==='overview'&&<Line dataKey="profit" name="صافي الربح" stroke="#60ccb2" strokeWidth={2.5} dot={{r:3,fill:'#60ccb2'}} activeDot={{r:5}} connectNulls={false}/>}</>}</ComposedChart></ResponsiveContainer>:<div className="blank-chart">ستظهر مقارنة الأشهر هنا بعد إضافة البيانات.</div>}</div></>;
}
