'use client';
import { useState,useEffect,useCallback } from 'react';
import Link from 'next/link';
import { Droplets,LayoutDashboard,TrendingUp,ReceiptText,Plus,CalendarDays,Database,Info,RefreshCw,CheckCircle2 } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { Skeleton } from '@/components/ui/skeleton';
import { MONTHS,FinanceData,View,demoData,summarize } from '@/lib/finance';
import { Choice,EmptyState } from './finance-ui';
import { Overview,Revenue,Expenses,SalesLedger,RecordSelection } from './finance-views';
import { SaleForm,ExpenseForm,SaveRecord } from './finance-forms';
const DEMO=demoData();
const titles:Record<View,string>={overview:'النظرة المالية العامة',revenue:'لوحة الإيرادات',expenses:'لوحة المصروفات',entry:'إدخال البيانات'};
const descriptions:Record<View,string>={overview:'تحليل المبيعات والمصروفات والربحية، ومقارنة النشاط على مدار أشهر 2026.',revenue:'جميع إيرادات المنتجات وتكاليفها، مع مقارنة الأصناف وهوامش الربح.',expenses:'تفصيل تكلفة المنتجات والمصروفات الثابتة والمتغيرة لكل شهر.',entry:'أضف بيانات المنتجات ومصروفات المحل لتتحدث المؤشرات والحسابات.'};
export default function FinanceApp({view}:{view:View}){
 const [source,setSource]=useState(view==='entry'?'actual':'demo'),[month,setMonth]=useState('all'),[category,setCategory]=useState('all'),[expenseType,setExpenseType]=useState('all'),[ready,setReady]=useState(false);
 const [actual,setActual]=useState<FinanceData|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const [editing,setEditing]=useState<RecordSelection|null>(null),[deleting,setDeleting]=useState<RecordSelection|null>(null),[deleteBusy,setDeleteBusy]=useState(false),[deleteError,setDeleteError]=useState('');
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setSource(view==='entry'?'actual':q.get('source')==='actual'?'actual':'demo');const m=q.get('month');if(m!==null&&/^(?:[0-9]|1[01])$/.test(m))setMonth(m);setReady(true)},[view]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/finance',{cache:'no-store'});const data=await response.json() as FinanceData & {error?:string};if(!response.ok)throw new Error(data.error||'تعذر تحميل البيانات.');if(!Array.isArray(data.sales)||!Array.isArray(data.expenses))throw new Error('تعذر قراءة البيانات. أعد المحاولة.');setActual(data);return true}catch(e){setError(e instanceof Error?e.message:'تعذر الاتصال الآن. أعد المحاولة.');return false}finally{setLoading(false)}},[]);
 useEffect(()=>{if(ready&&source==='actual')void load()},[ready,source,load]);
 useEffect(()=>{if(!ready)return;const query=new URLSearchParams();query.set('source',source);if(month!=='all')query.set('month',month);window.history.replaceState(null,'',`${window.location.pathname}?${query}`)},[source,month,ready]);
 const save:SaveRecord=async(payload,method)=>{const response=await fetch('/api/finance',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let result:{count?:number;error?:string};try{result=await response.json() as typeof result}catch{throw new Error('لم يصل تأكيد الحفظ. احتفظ بالبيانات وأعد المحاولة.')}if(!response.ok)throw new Error(result.error||'تعذر الحفظ.');const refreshed=await load();setSuccess(`${method==='PUT'?'تم حفظ التعديل':Number(result.count)>1?`تم حفظ ${result.count} مصروفات شهرية`:'تم حفظ السجل'}${refreshed?' وتحديث البيانات.':'؛ تعذر تحديث العرض، اضغط إعادة التحميل.'}`);return result};
 async function remove(){if(!deleting)return;setDeleteBusy(true);setDeleteError('');try{const response=await fetch('/api/finance',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:deleting.kind,id:deleting.row.id,version:deleting.row.version})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'تعذر الحذف.');setDeleting(null);await load();setSuccess('تم حذف السجل وتحديث البيانات.')}catch(e){setDeleteError(e instanceof Error?e.message:'تعذر الحذف. أعد المحاولة.')}finally{setDeleteBusy(false)}}
 const data=source==='demo'?DEMO:actual||{sales:[],expenses:[]};
 const query=`source=${source}${month!=='all'?`&month=${month}`:''}`;
 const nav=[{view:'overview',label:'نظرة عامة',path:'/',icon:<LayoutDashboard/>},{view:'revenue',label:'الإيرادات',path:'/revenue',icon:<TrendingUp/>},{view:'expenses',label:'المصروفات',path:'/expenses',icon:<ReceiptText/>},{view:'entry',label:'إدخال البيانات',path:'/entry',icon:<Plus/>}];
 const actions={actual:source==='actual',onEdit:setEditing,onDelete:(r:RecordSelection)=>{setDeleteError('');setDeleting(r)}};
 return <><a href="#main" className="skip-link">انتقل إلى المحتوى</a><div className="shell"><header className="brandbar"><Link href={`/?${query}`} className="brand"><span className="brand-mark"><Droplets size={25}/></span><span><strong>جوس لاين</strong><small>JUICE LINE</small></span></Link><div className="brand-meta"><span>تبوك · الإدارة المالية</span><span>السنة المالية <b dir="ltr">2026</b></span></div></header><div className="top-nav"><nav className="nav-links" aria-label="صفحات النظام المالي">{nav.map(n=><Link key={n.view} href={`${n.path}?${n.view==='entry'?'source=actual':query}`} className={`nav-link ${view===n.view?'active':''}`} aria-current={view===n.view?'page':undefined}>{n.icon}{n.label}</Link>)}</nav><span className="year-pill"><CalendarDays size={15}/>01 يناير — 31 ديسمبر 2026</span></div><main id="main"><header className="page-top"><div><div className="eyebrow">JUICE LINE / FINANCE 2026</div><h1>{titles[view]}</h1><p>{descriptions[view]}</p></div>{view!=='entry'&&<Link className="action-button" href="/entry?source=actual"><Plus/>إضافة بيانات</Link>}</header>
 {view!=='entry'?<div className="toolbar"><div className="toolbar-filters"><div className="select-field"><label htmlFor="month-filter">الفترة المعروضة</label><Choice id="month-filter" label="الفترة المعروضة" value={month} onChange={setMonth} options={[{value:'all',label:'كل الأشهر · 2026'},...MONTHS.map((m,i)=>({value:String(i),label:m+' 2026'}))]}/></div>{view==='revenue'&&<div className="select-field"><label htmlFor="category-filter">تصنيف المنتج</label><Choice id="category-filter" label="تصنيف المنتج" value={category} onChange={setCategory} options={[{value:'all',label:'جميع التصنيفات'},...[...new Set(data.sales.map(s=>s.category))].map(c=>({value:c,label:c}))]}/></div>}{view==='expenses'&&<div className="select-field"><label htmlFor="type-filter">نوع المصروف</label><Choice id="type-filter" label="نوع المصروف" value={expenseType} onChange={setExpenseType} options={[{value:'all',label:'جميع المصروفات'},{value:'product',label:'تكلفة المنتجات'},{value:'fixed',label:'مصروفات ثابتة'},{value:'variable',label:'مصروفات متغيرة'}]}/></div>}</div><div className="source-filter"><span className="source-label">البيانات</span><Choice label="مصدر البيانات" value={source} onChange={v=>{setSource(v);setCategory('all');setSuccess('')}} options={[{value:'demo',label:'نموذج افتراضي للعرض'},{value:'actual',label:'بيانات المحل المحفوظة'}]}/>{source==='actual'&&<button className="icon-button" disabled={loading} onClick={()=>void load()} aria-label="تحديث البيانات"><RefreshCw size={17}/></button>}</div></div>:<div className="source-summary"><Database size={16} style={{display:'inline',marginLeft:8}}/>الإدخالات تُحفظ ضمن «بيانات المحل المحفوظة»، وتُعرض مستقلة عن النموذج الافتراضي.</div>}
 {source==='demo'&&<div className="demo-note"><Info/>جميع أرقام وأصناف الأشهر الاثني عشر افتراضية للعرض، ولا تمثل بيانات جوس لاين الفعلية.</div>}
 {success&&<div className="success-message" role="status"><CheckCircle2 size={18}/>{success}</div>}
 {view==='entry'?<><Tabs defaultValue="sale" dir="rtl"><TabsList className="entry-tabs"><TabsTrigger className="entry-tab" value="sale">إيراد وتكلفة منتج</TabsTrigger><TabsTrigger className="entry-tab" value="expense">مصروفات المحل</TabsTrigger></TabsList><TabsContent className="entry-panel" value="sale" forceMount><SaleForm onSave={save}/></TabsContent><TabsContent className="entry-panel" value="expense" forceMount><ExpenseForm onSave={save}/></TabsContent></Tabs><div className="section-heading"><div><h2>إيرادات المنتجات المحفوظة</h2><p>راجع سجلاتك وعدّلها من هنا، أو افتح صفحة المصروفات لمراجعة التشغيل.</p></div></div>{error?<div className="error-panel" role="alert"><p>{error}</p><button className="action-button secondary" onClick={()=>void load()}>إعادة التحميل</button></div>:loading&&!actual?<div className="loading-panel">جاري تحميل السجلات...</div>:<SalesLedger sales={actual?.sales||[]} {...actions} actual/>}</>:source==='actual'&&error?<div className="error-panel" role="alert"><h2>تعذر تحديث البيانات</h2><p>{error}</p><button className="action-button secondary" onClick={()=>void load()}><RefreshCw/>إعادة المحاولة</button></div>:source==='actual'&&(!ready||loading&&!actual)?<div aria-label="جاري تحميل البيانات" role="status"><p className="muted-text">جاري تحميل بيانات المحل...</p><div className="skeleton-grid">{[0,1,2,3].map(i=><Skeleton key={i} className="skeleton-box"/>)}</div><Skeleton className="skeleton-box" style={{height:350,marginTop:22}}/></div>:<>{source==='actual'&&summarize(data).records===0&&<EmptyState title="ابدأ بيانات المحل من هنا" description="لا توجد سجلات محفوظة حتى الآن. أضف إيرادات المنتجات ومصروفات التشغيل، وستُحسب النتائج لكل شهر تلقائيًا."><Link href="/entry?source=actual" className="action-button"><Plus/>إدخال أول سجل</Link></EmptyState>}{view==='overview'&&<Overview data={data} month={month} onMonth={setMonth}/>} {view==='revenue'&&<Revenue data={data} month={month} category={category} {...actions}/>} {view==='expenses'&&<Expenses data={data} month={month} expenseType={expenseType} {...actions}/>}</>}
 </main><footer className="footer"><span>جوس لاين · النظام المالي 2026</span><span>إعداد يوسف — مؤسسة الريادة البصرية</span><p>الأرقام بالريال وغير شاملة ضريبة القيمة المضافة. التحليل مبني على الإيرادات والتكاليف المسجلة. نموذج العرض الافتراضي مستقل عن بيانات المحل.</p></footer></div>
 <Dialog open={!!editing} onOpenChange={open=>{if(!open)setEditing(null)}}><DialogContent className="edit-dialog" dir="rtl"><DialogHeader><DialogTitle style={{textAlign:'right'}}>{editing?.kind==='sale'?'تعديل بيانات المنتج':'تعديل مصروف التشغيل'}</DialogTitle><DialogDescription style={{textAlign:'right'}}>تتحدث الحسابات المرتبطة بهذا السجل بعد الحفظ.</DialogDescription></DialogHeader>{editing?.kind==='sale'?<SaleForm key={editing.row.id} initial={editing.row} onSave={save} onDone={()=>setEditing(null)}/>:editing?.kind==='expense'?<ExpenseForm key={editing.row.id} initial={editing.row} onSave={save} onDone={()=>setEditing(null)}/>:null}</DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={open=>{if(!open&&!deleteBusy)setDeleting(null)}}><AlertDialogContent className="confirm-dialog"><AlertDialogHeader><AlertDialogTitle>حذف هذا السجل؟</AlertDialogTitle><AlertDialogDescription>{deleting?.kind==='sale'?`سيُحذف سجل «${deleting.row.product}» بتاريخ ${deleting.row.date} وإيراده وتكلفته معًا.`:deleting?`سيُحذف مصروف «${deleting.row.title}» بتاريخ ${deleting.row.date} فقط، دون بقية الأشهر.`:''} لا يمكن التراجع عن الحذف.</AlertDialogDescription></AlertDialogHeader>{deleteError&&<div className="inline-error dialog-error" role="alert">{deleteError}</div>}<AlertDialogFooter><AlertDialogCancel disabled={deleteBusy}>إلغاء</AlertDialogCancel><AlertDialogAction disabled={deleteBusy} onClick={event=>{event.preventDefault();void remove()}} className="bg-destructive text-background hover:bg-destructive/90">{deleteBusy?'جاري الحذف...':'حذف السجل'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}
